### ISSUE TITLE
Ability to integrate KVS with ReactJs?

### ISSUE THREAD

**Issue by nhockool1002** [matwerber1/aws-kinesisvideo-webrtc-react#1]
I'm researching this for my project, I don't know how difficult is the possibility of KVS combined with ReactJs? Can I use your develop branch to run? I am researching but don't know where to start yet, glad to have found your repositories.

**Comment by matwerber1** [comment]
For sure! it's definitely doable... there are already existing demos of using Kinesis Streams and Kinesis Video and WebRTC in the browser with vanilla JS, so no reason it can't be done in React.

Keep in mind, there are is the "standard" Kinesis Video Streams and then there is the relatively new "Kinesis WebRTC Signaling Channels".  The standard KVS is really built for ingesting video and processing it, e.g. security cam footage and then sending alerts. It has a few seconds end-to-end delay. Kinesis WebRTC is built for super low latency live, two-way communication. 

This project focuses on Kinesis WebRTC. I'm basically trying to port the demo from https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js into React. I got sidetracked and never finished it... it's partially complete... but needs work (and I'm only basic skillset with React).

**Comment by matwerber1** [comment]
I'm working on rewriting this to be cleaner... don't like the way I did it. Stay tuned.

**Comment by matwerber1** [comment]
I just rewrote everything - everything (seems to be!) working and its far cleaner that my previous version. Let me know if it helps?

**Comment by matwerber1** [comment]
Just uploaded the built app to github pages, you can demo it if you like: 
https://matwerber1.github.io/aws-kinesisvideo-webrtc-react/

**Comment by nhockool1002** [comment]
Thank you it's awesome, I also continued your project to implement it into ReactJS, I also preliminary completed it. Thank you very much for the feedback.

**Comment by matwerber1** [comment]
Glad to hear. Let me know if you have any feedback! It's quite possible I may not have converted it 100% accurately :)

**Comment by matwerber1** [comment]
If you're interested, I used this same code but integrated it into an AWS Amplify project so that you don't need to enter AWS access keys. The Amplify project creates a Cognito User Pool and authenticated users are granted temporary IAM permissions. I haven't updated the readme screenshots, but it does contain the KVS WebRTC widget:
https://github.com/matwerber1/aws-amplify-react-toolkit
